import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={{
          with: "100%",
          background: "teal",
          fontSize: "30px",
          display: "flex",
          justifyContent: "center"
        }}
        >
          <Link style={{ margin: "10px"}}href="/" >home</Link>
          <Link style={{ margin: "10px"}}href="/posts" >posts</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
